// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RandomURLInterface is an autogenerated mock type for the RandomURLInterface type
type RandomURLInterface struct {
	mock.Mock
}

// RandomURL provides a mock function with given fields: size
func (_m *RandomURLInterface) RandomURL(size int) string {
	ret := _m.Called(size)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(size)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewRandomURLInterface creates a new instance of RandomURLInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandomURLInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RandomURLInterface {
	mock := &RandomURLInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
